### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Roeis** [Roeis/H5-Factory#1]
- [x] cancel mechanism
- [x] add rotate function
- [ ] add new mobile ui component MU
- [ ] add template mechanism
- [ ] add hotkey
